name: example
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  easy_ads_flutter: ^26.3.12
  easy_prank_call:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/videos/